### ISSUE TITLE
Install fails using npm

### ISSUE THREAD

**Issue by hitchcott** [bitcoin/secp256k1#335]
https://github.com/iurimatias/embark-framework/issues/99

Here is the output of `npm install secp256k1@1.1.1 -g`:

```
> secp256k1@1.1.1 install /usr/local/lib/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/functions.o
../functions.cc:66:16: error: no matching member function for call to 'Set'
      results->Set(0, node::Buffer::New(output, outputlen));
      ~~~~~~~~~^~~
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:1491:17: note: candidate function not viable: no known conversion from 'node::Buffer *' to 'Handle<v8::Value>' for 2nd
      argument
  V8EXPORT bool Set(uint32_t index,
                ^
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:1487:17: note: candidate function not viable: no known conversion from 'int' to 'Handle<v8::Value>' for 1st argument
  V8EXPORT bool Set(Handle<Value> key,
                ^
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:281:46: error: no matching constructor for initialization of 'Handle<v8::Value>'
  template <class S> inline Local(S* that) : Handle<T>(that) { }
                                             ^         ~~~~
.././async.h:40:7: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<node::Buffer>' requested here
      node::Buffer::New(output, outputlen),
      ^
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:174:26: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'node::Buffer *'
      to 'const v8::Handle<v8::Value>' for 1st argument
template <class T> class Handle {
                         ^
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:184:19: note: candidate constructor not viable: no known conversion from 'node::Buffer *' to 'v8::Value *' for 1st
      argument
  inline explicit Handle(T* val) : val_(val) {}
                  ^
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:196:29: note: candidate template ignored: could not match 'Handle<type-parameter-0-0>' against 'node::Buffer *'
  template <class S> inline Handle(Handle<S> that)
                            ^
/Users/chris/.node-gyp/0.10.39/deps/v8/include/v8.h:179:10: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  inline Handle() : val_(0) {}
         ^
In file included from ../functions.cc:1:
In file included from ../node_modules/nan/nan.h:140:
In file included from ../node_modules/nan/nan_callbacks.h:120:
../node_modules/nan/nan_callbacks_pre_12_inl.h:97:34: error: assigning to 'node::Buffer **volatile' from incompatible type 'v8::Primitive *'
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:124:40: note: expanded from macro 'TYPE_CHECK'
      *(static_cast<T *volatile *>(0)) = static_cast<S*>(0);                   \
                                       ^ ~~~~~~~~~~~~~~~~~~
../functions.cc:106:29: note: in instantiation of function template specialization 'Nan::ReturnValue<v8::Value>::Set<node::Buffer>' requested here
      info.GetReturnValue().Set(node::Buffer::New((char *)output, outputlen));
                            ^
3 errors generated.
make: *** [Release/obj.target/secp256k1/functions.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/secp256k1
gyp ERR! node -v v0.10.39
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "secp256k1@1.1.1" "-g"
npm ERR! node v0.10.39
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@1.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chris/git/ether/http-getter-passthrough/npm-debug.log
```

**Comment by hitchcott** [comment]
X-posted to https://github.com/wanderer/secp256k1-node/issues/35

**Comment by sipa** [comment]
This doesn't look like a problem with the C code.

**Comment by hitchcott** [comment]
Yes, closing. Apologies for the false alarm.
